import { GamingPlatform, GlobalConfig, WinnerTickerItem } from './types';

export const initialGlobalConfig: GlobalConfig = {
  heroHeadline: "Stop Wasting Money on Unverified Sites. Claim Your 100% Guaranteed Welcome Bonuses",
  heroSubheading: "Verified, licensed platforms with instant withdrawals, high RTP slots, and up to $1,500 + 500% first deposit bonuses.",
  topBannerTemplate: "🔥 Top Verified Gaming Sites available in {{country}} today!",
  enableLuckyWheel: true,
  enableLiveWinnersTicker: true,
  enableBotCloaking: true,
  enableSubPartnerProgram: true,
  subPartnerHeadline: "Become an Official Gaming Sub-Partner & Earn 45%-50% Lifetime RevShare",
  featuredPrizePlatformId: "1win",
  featuredPromoCode: "VIPBONUS500",
  wheelBonusText: "500% WELCOME BONUS + 200 FREE SPINS",
  // Standalone Custom Coupons
  customCoupons: [
    {
      id: "coupon_ipl2026",
      brandName: "Megapari",
      title: "IPL 2026 Cricket Special 100% Free Bet",
      code: "MEGACRICKET500",
      description: "Get 100% risk-free cricket bet up to ₹10,000 / $150 + 50 free spins on registration.",
      targetUrl: "https://megapari.com/?ref=VIPCRICKET",
      category: "Cricket & Sports",
      badgeText: "IPL 2026 SPECIAL",
      isActive: true,
      metaTitle: "Megapari Promo Code MEGACRICKET500 | Free Bet 2026",
      metaDescription: "Claim 100% risk free cricket bet with code MEGACRICKET500 on Megapari.",
      clicksCount: 340,
      copiesCount: 210
    },
    {
      id: "coupon_melbet",
      brandName: "Melbet",
      title: "Melbet Mega Deposit Boost 200%",
      code: "MELVIPMAX",
      description: "Unlock 200% first deposit bonus up to $250 + instant VIP cashback.",
      targetUrl: "https://melbet.com/?tag=VIPPROMO",
      category: "Casino & Slots",
      badgeText: "LIMITED TIME",
      isActive: true,
      metaTitle: "Melbet Promo Code MELVIPMAX | 200% Deposit Bonus",
      metaDescription: "Get official Melbet promo code MELVIPMAX for 200% deposit bonus.",
      clicksCount: 280,
      copiesCount: 175
    }
  ],
  // Tracking Pixels & Feedback
  globalTrackingPixels: {
    platformId: 'global',
    facebookPixelId: '123456789012345',
    googleAnalyticsId: 'G-MEASUREMENT123'
  },
  approvedFeedbacks: [
    {
      id: "fb_1",
      platformId: "1win",
      platformName: "1Win",
      userName: "Alex R.",
      rating: 5,
      comment: "Used promo code MAXBOOST500 during sign up and got 500% deposit bonus instantly! Instant UPI withdrawal worked in 5 minutes.",
      createdAt: "2026-08-09T14:30:00.000Z",
      isApproved: true
    },
    {
      id: "fb_2",
      platformId: "mostbet",
      platformName: "Mostbet",
      userName: "Rahul K.",
      rating: 5,
      comment: "Great odds on IPL matches and fast customer support via Telegram. Code works 100%.",
      createdAt: "2026-08-08T18:20:00.000Z",
      isApproved: true
    },
    {
      id: "fb_3",
      platformId: "stake",
      platformName: "Stake.com",
      userName: "Marco P.",
      rating: 4,
      comment: "VIP rakeback and instant crypto payout. Smooth registration experience.",
      createdAt: "2026-08-07T09:15:00.000Z",
      isApproved: true
    }
  ],
  // Social Media Channels
  telegramUrl: "https://t.me/BonusPromoCodeOfficial",
  instagramUrl: "https://instagram.com/bonuspromocode",
  tiktokUrl: "https://tiktok.com/@bonuspromocode",
  whatsappGroupUrl: "https://chat.whatsapp.com/BonusPromoCodeClub",
  youtubeUrl: "https://youtube.com/@BonusPromoCode",
  // FCM Push Notifications & A/B Testing Defaults
  pushNotifications: [
    {
      id: "pn_101",
      title: "🔥 500% FLASH BONUS ACTIVATED!",
      body: "Use promo code MAXBOOST500 on 1Win now. Extra 50 Free Spins ends in 1 hour!",
      type: "flash_bonus",
      targetPlatformId: "1win",
      targetPlatformName: "1Win",
      sentAt: "2026-08-10T08:00:00.000Z",
      recipientCount: 1420,
      promoCode: "MAXBOOST500",
      actionUrl: "/go/1win"
    },
    {
      id: "pn_102",
      title: "⚡ NEW ARRIVAL: Megapari 200% VIP Pass",
      body: "Exclusive code MEGAPRO200 is now live for instant casino & sports betting.",
      type: "new_arrival",
      targetPlatformId: "megapari",
      targetPlatformName: "Megapari",
      sentAt: "2026-08-09T16:30:00.000Z",
      recipientCount: 980,
      promoCode: "MEGAPRO200",
      actionUrl: "/go/megapari"
    }
  ],
  abTestConfig: {
    enabled: true,
    heroDesign: "variant_a",
    buttonColor: "amber",
    stats: {
      variantAViews: 3420,
      variantBViews: 3180,
      variantAClicks: 890,
      variantBClicks: 1140
    }
  },
  partnerPanelConfigs: [
    {
      platformId: "1win",
      platformName: "1Win Casino & Sports",
      apiKey: "1WIN_AFF_883921_SECRET",
      partnerApiUrl: "https://api.1win-partners.com/v2/stats",
      affiliateId: "1WIN_883921",
      postbackKey: "pb_1win_2026_xyz",
      syncEnabled: true,
      lastSyncedAt: new Date().toISOString(),
      stats: {
        totalRegistrations: 642,
        ftdCount: 418,
        totalDepositsAmount: 24850,
        netGamingRevenue: 18420,
        commissionEarned: 9210,
        revSharePercent: 50
      }
    },
    {
      platformId: "mostbet",
      platformName: "Mostbet Official",
      apiKey: "MOSTBET_KEY_992014",
      partnerApiUrl: "https://mostbet-partners.com/api/v1/reports",
      affiliateId: "MOST_992014",
      postbackKey: "pb_mostbet_882",
      syncEnabled: true,
      lastSyncedAt: new Date().toISOString(),
      stats: {
        totalRegistrations: 415,
        ftdCount: 260,
        totalDepositsAmount: 14200,
        netGamingRevenue: 11500,
        commissionEarned: 5175,
        revSharePercent: 45
      }
    },
    {
      platformId: "pinup",
      platformName: "Pin-Up Casino",
      apiKey: "PINUP_SECRET_44210",
      partnerApiUrl: "https://pin-up.partners/api/stats",
      affiliateId: "PINUP_44210",
      postbackKey: "pb_pinup_993",
      syncEnabled: true,
      lastSyncedAt: new Date().toISOString(),
      stats: {
        totalRegistrations: 380,
        ftdCount: 245,
        totalDepositsAmount: 12800,
        netGamingRevenue: 9800,
        commissionEarned: 4410,
        revSharePercent: 45
      }
    },
    {
      platformId: "1xbet",
      platformName: "1xBet Partners",
      apiKey: "1XBET_API_77391",
      partnerApiUrl: "https://1xbet-partners.com/api/statistics",
      affiliateId: "1X_77391",
      postbackKey: "pb_1x_1029",
      syncEnabled: true,
      lastSyncedAt: new Date().toISOString(),
      stats: {
        totalRegistrations: 290,
        ftdCount: 185,
        totalDepositsAmount: 9400,
        netGamingRevenue: 7200,
        commissionEarned: 2880,
        revSharePercent: 40
      }
    }
  ],
  // Security & Admin Link Hiding
  hideAdminLink: true,
  secretKeyTrigger: "Ctrl+Shift+A",
  // Email Eligibility Checker Settings
  strictEmailChecking: true,
  registeredEmailsList: [
    "lokeshrao050@gmail.com",
    "user@example.com",
    "test@gmail.com",
    "admin@1win.com",
    "player1@gmail.com"
  ]
};

export const initialPlatforms: GamingPlatform[] = [
  {
    id: "1win",
    slug: "1win",
    name: "1Win Casino & Sports",
    logoUrl: "https://www.google.com/s2/favicons?domain=1win.pro&sz=256",
    rating: 9.9,
    starRating: 5,
    averageUserRating: 4.8,
    totalReviewsCount: 13968,
    badges: ["Instant UPI/Pix/Crypto", "No KYC Required", "24/7 Live Support", "High RTP Slots"],
    bonusText: "Get 500% Welcome Bonus + 100 Free Spins",
    promoCode: "500TOPUP",
    rawAffiliateUrl: "https://one-vv8838.com/casino/list?open=register&p=lkq7",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: true,
    featuredRank: 1, // Gold
    isActive: true,
    clicksCount: 1420,
    copiesCount: 890,
    category: "Casino & Sportsbook",
    metaTitle: "1Win Casino & Sports Promo Code 500TOPUP | Best Bonus 2026",
    metaDescription: "Use verified promo code 500TOPUP for 1Win Casino & Sports to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "1win casino & sports promo code, 1win casino & sports bonus, MAXBOOST500, best 1win casino & sports promo",
    reviewContent: `
      # 1Win Casino & Sports Review 2026
      1Win is an industry-leading online gaming hub offering over 10,000 slots, live casino tables, crash games (Aviator, JetX), and sports betting.
      
      ### Key Highlights
      - **Instant Payouts:** Fast processing via UPI, Pix, USDT, Crypto, and Visa/Mastercard.
      - **Huge Welcome Bonus:** Up to 500% on first 4 deposits.
      - **Anonymity:** Fast 1-click registration without lengthy verification.
    `
  },
  {
    id: "mostbet",
    slug: "mostbet",
    name: "Mostbet Official",
    logoUrl: "https://www.google.com/s2/favicons?domain=mostbet.com&sz=256",
    rating: 9.7,
    starRating: 5,
    averageUserRating: 4.9,
    totalReviewsCount: 30132,
    badges: ["Fast Deposit Boost", "125% Sports Bonus", "Fast Cashouts", "Licensed Platform"],
    bonusText: "125% Bonus up to $300 + 250 Free Spins",
    promoCode: "MOSTBONUSVIP",
    rawAffiliateUrl: "https://mostbet.com/signup?partner=VIPGAMES",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: true,
    featuredRank: 2, // Silver
    isActive: true,
    clicksCount: 1105,
    copiesCount: 630,
    category: "Sportsbook & Slots",
    metaTitle: "Mostbet Official Promo Code MOSTBONUSVIP | Best Bonus 2026",
    metaDescription: "Use verified promo code MOSTBONUSVIP for Mostbet Official to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "mostbet official promo code, mostbet official bonus, MOSTBONUSVIP, best mostbet official promo",
    reviewContent: `
      # Mostbet Review
      Mostbet provides incredible sports odds, esports wagering, and top-tier slot provider integrations.
      
      ### Why Choose Mostbet?
      - 24/7 Customer Care
      - Express bet boosts up to 40% extra winnings.
    `
  },
  {
    id: "pinup",
    slug: "pinup",
    name: "Pin-Up Casino",
    logoUrl: "https://www.google.com/s2/favicons?domain=pin-up.casino&sz=256",
    rating: 9.6,
    starRating: 5,
    averageUserRating: 4.9,
    totalReviewsCount: 46796,
    badges: ["250 Free Spins", "Daily Cashback 10%", "Instant E-Wallets"],
    bonusText: "120% Bonus + 250 Free Spins on 1st Deposit",
    promoCode: "PINUPVIP2026",
    rawAffiliateUrl: "https://pin-up.casino/?promo=PINUPSUPER",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: true,
    featuredRank: 3, // Bronze
    isActive: true,
    clicksCount: 880,
    copiesCount: 410,
    category: "Live Casino & Slots",
    metaTitle: "Pin-Up Casino Promo Code PINUPVIP2026 | Best Bonus 2026",
    metaDescription: "Use verified promo code PINUPVIP2026 for Pin-Up Casino to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "pin-up casino promo code, pin-up casino bonus, PINUPVIP2026, best pin-up casino promo",
    reviewContent: `
      # Pin-Up Casino Review
      Retro themed casino with ultra modern payment methods and fast withdrawals.
    `
  },
  {
    id: "stake",
    slug: "stake",
    name: "Stake Crypto Casino",
    logoUrl: "https://www.google.com/s2/favicons?domain=stake.com&sz=256",
    rating: 9.5,
    starRating: 5,
    averageUserRating: 4.8,
    totalReviewsCount: 35318,
    badges: ["Zero Fee Withdrawals", "VIP Rakeback", "Instant Crypto"],
    bonusText: "200% Deposit Match + VIP Level Up Boost",
    promoCode: "STAKEPRO2026",
    rawAffiliateUrl: "https://stake.com/?c=VIPPROMO",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 750,
    copiesCount: 320,
    category: "Crypto Gaming",
    metaTitle: "Stake Crypto Casino Promo Code STAKEPRO2026 | Best Bonus 2026",
    metaDescription: "Use verified promo code STAKEPRO2026 for Stake Crypto Casino to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "stake crypto casino promo code, stake crypto casino bonus, STAKEPRO2026, best stake crypto casino promo",
    reviewContent: `
      # Stake.com Official Partner
      The world's biggest crypto casino with provably fair games and instant payouts.
    `
  },
  {
    id: "bcgame",
    slug: "bcgame",
    name: "BC.Game VIP",
    logoUrl: "https://www.google.com/s2/favicons?domain=bc.game&sz=256",
    rating: 9.4,
    starRating: 5,
    averageUserRating: 4.9,
    totalReviewsCount: 12510,
    badges: ["180% First Deposit", "Daily Spin Rewards", "No Limits"],
    bonusText: "Up to 360% Deposit Match across 4 deposits",
    promoCode: "982zzt4b7s",
    rawAffiliateUrl: "https://bc.game/i-982zzt4b7s-n/",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 620,
    copiesCount: 290,
    category: "Crypto & Crash Games"
  ,
    metaTitle: "BC.Game VIP Promo Code 982zzt4b7s | Best Bonus 2026",
    metaDescription: "Use verified promo code 982zzt4b7s for BC.Game VIP to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "bc.game vip promo code, bc.game vip bonus, 982zzt4b7s, best bc.game vip promo"
  },
  {
    id: "parimatch",
    slug: "parimatch",
    name: "Parimatch Global",
    logoUrl: "https://www.google.com/s2/favicons?domain=parimatch.com&sz=256",
    rating: 9.3,
    starRating: 4,
    averageUserRating: 4.9,
    totalReviewsCount: 20403,
    badges: ["Cricket & Football Odds", "UPI / NetBanking", "Official Sponsor"],
    bonusText: "150% Sports Bonus up to $200",
    promoCode: "PARIBONUS",
    rawAffiliateUrl: "https://parimatch.com/?btag=VIP123",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 540,
    copiesCount: 180,
    category: "Sportsbook"
  ,
    metaTitle: "Parimatch Global Promo Code PARIBONUS | Best Bonus 2026",
    metaDescription: "Use verified promo code PARIBONUS for Parimatch Global to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "parimatch global promo code, parimatch global bonus, PARIBONUS, best parimatch global promo"
  }  ,
  {
    id: "ggbet",
    slug: "ggbet",
    name: "GG.BET",
    logoUrl: "https://www.google.com/s2/favicons?domain=gg.bet&sz=256",
    rating: 9.6,
    starRating: 5,
    averageUserRating: 4.7,
    totalReviewsCount: 25971,
    badges: ["Esports Focus", "Live Streams", "Fast Crypto Payouts", "High Odds"],
    bonusText: "200% Deposit Bonus + Free Bet",
    promoCode: "GGBONUS200",
    rawAffiliateUrl: "https://gg.bet/en/betting?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 840,
    copiesCount: 310,
    category: "Esports Betting"
  ,
    metaTitle: "GG.BET Promo Code GGBONUS200 | Best Bonus 2026",
    metaDescription: "Use verified promo code GGBONUS200 for GG.BET to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "gg.bet promo code, gg.bet bonus, GGBONUS200, best gg.bet promo"
  },
  {
    id: "betway",
    slug: "betway",
    name: "Betway Esports",
    logoUrl: "https://www.google.com/s2/favicons?domain=betway.com&sz=256",
    rating: 9.5,
    starRating: 5,
    averageUserRating: 4.8,
    totalReviewsCount: 45239,
    badges: ["Global Brand", "CS:GO Sponsor", "Safe & Legal", "Daily Boosts"],
    bonusText: "100% Match up to ₹2500 / $30",
    promoCode: "BETWAYVIP",
    rawAffiliateUrl: "https://betway.com/en/sports/cat/esports?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 750,
    copiesCount: 200,
    category: "Esports Betting"
  ,
    metaTitle: "Betway Esports Promo Code BETWAYVIP | Best Bonus 2026",
    metaDescription: "Use verified promo code BETWAYVIP for Betway Esports to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "betway esports promo code, betway esports bonus, BETWAYVIP, best betway esports promo"
  },
  {
    id: "rivalry",
    slug: "rivalry",
    name: "Rivalry",
    logoUrl: "https://www.google.com/s2/favicons?domain=rivalry.com&sz=256",
    rating: 9.4,
    starRating: 5,
    averageUserRating: 4.8,
    totalReviewsCount: 18678,
    badges: ["Made for Gamers", "Instant Withdrawals", "Unique Markets", "Meme Friendly"],
    bonusText: "100% Welcome Bonus up to $100",
    promoCode: "RIVALRY100",
    rawAffiliateUrl: "https://www.rivalry.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 420,
    copiesCount: 150,
    category: "Esports Betting"
  ,
    metaTitle: "Rivalry Promo Code RIVALRY100 | Best Bonus 2026",
    metaDescription: "Use verified promo code RIVALRY100 for Rivalry to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "rivalry promo code, rivalry bonus, RIVALRY100, best rivalry promo"
  },
  {
    id: "thunderpick",
    slug: "thunderpick",
    name: "Thunderpick",
    logoUrl: "https://www.google.com/s2/favicons?domain=thunderpick.io&sz=256",
    rating: 9.2,
    starRating: 4,
    averageUserRating: 4.8,
    totalReviewsCount: 45881,
    badges: ["Crypto Exclusive", "VIP Rewards", "Esports Live Betting"],
    bonusText: "100% First Deposit Bonus up to €500",
    promoCode: "THUNDER500",
    rawAffiliateUrl: "https://thunderpick.io/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 310,
    copiesCount: 90,
    category: "Crypto Esports"
  ,
    metaTitle: "Thunderpick Promo Code THUNDER500 | Best Bonus 2026",
    metaDescription: "Use verified promo code THUNDER500 for Thunderpick to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "thunderpick promo code, thunderpick bonus, THUNDER500, best thunderpick promo"
  },
  {
    id: "pinnacle",
    slug: "pinnacle",
    name: "Pinnacle Esports",
    logoUrl: "https://www.google.com/s2/favicons?domain=pinnacle.com&sz=256",
    rating: 9.7,
    starRating: 5,
    averageUserRating: 4.9,
    totalReviewsCount: 30356,
    badges: ["Highest Odds", "No Limit Betting", "Sharp Bettors Welcome"],
    bonusText: "Best Esports Odds Guaranteed",
    promoCode: "PINNACLEVIP",
    rawAffiliateUrl: "https://www.pinnacle.com/en/esports/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 680,
    copiesCount: 110,
    category: "Esports Betting"
  ,
    metaTitle: "Pinnacle Esports Promo Code PINNACLEVIP | Best Bonus 2026",
    metaDescription: "Use verified promo code PINNACLEVIP for Pinnacle Esports to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "pinnacle esports promo code, pinnacle esports bonus, PINNACLEVIP, best pinnacle esports promo"
  },
  {
    id: "1xbet",
    slug: "1xbet",
    name: "1xBet",
    logoUrl: "https://www.google.com/s2/favicons?domain=1xbet.com&sz=256",
    rating: 9.3,
    starRating: 4,
    averageUserRating: 4.8,
    totalReviewsCount: 41354,
    badges: ["Massive Markets", "High Odds", "Fast Local Payments", "Navi Sponsor"],
    bonusText: "130% First Deposit Bonus up to ₹33000",
    promoCode: "1x_5482230",
    rawAffiliateUrl: "https://reffpa.com/L?tag=d_5793442m_1236c_&site=5793442&ad=1236",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 920,
    copiesCount: 450,
    category: "Sportsbook"
  ,
    metaTitle: "1xBet Promo Code 1x_5482230 | Best Bonus 2026",
    metaDescription: "Use verified promo code 1x_5482230 for 1xBet to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "1xbet promo code, 1xbet bonus, 1XBETMAX, best 1xbet promo"
  }  ,
  {
    id: "rajabets",
    slug: "rajabets",
    name: "Rajabets",
    logoUrl: "https://www.google.com/s2/favicons?domain=rajabets.com&sz=256",
    rating: 9.6,
    starRating: 5,
    averageUserRating: 5.0,
    totalReviewsCount: 41544,
    badges: ["Instant UPI", "Indian Focus", "Hindi Support", "Cricket Specials"],
    bonusText: "150% Sports Welcome Bonus up to ₹100,000",
    promoCode: "RAJABOOST",
    rawAffiliateUrl: "https://rajabets.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 950,
    copiesCount: 420,
    category: "Indian Sportsbook"
  ,
    metaTitle: "Rajabets Promo Code RAJABOOST | Best Bonus 2026",
    metaDescription: "Use verified promo code RAJABOOST for Rajabets to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "rajabets promo code, rajabets bonus, RAJABOOST, best rajabets promo"
  },
  {
    id: "dafabet",
    slug: "dafabet",
    name: "Dafabet India",
    logoUrl: "https://www.google.com/s2/favicons?domain=dafabet.com&sz=256",
    rating: 9.5,
    starRating: 5,
    averageUserRating: 4.8,
    totalReviewsCount: 18703,
    badges: ["Most Trusted", "Local Bank Transfer", "Exchange Betting"],
    bonusText: "170% First Deposit Bonus up to ₹17,000",
    promoCode: "DAFA170",
    rawAffiliateUrl: "https://www.dafabet.com/in/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 880,
    copiesCount: 390,
    category: "Sportsbook & Exchange"
  ,
    metaTitle: "Dafabet India Promo Code DAFA170 | Best Bonus 2026",
    metaDescription: "Use verified promo code DAFA170 for Dafabet India to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "dafabet india promo code, dafabet india bonus, DAFA170, best dafabet india promo"
  },
  {
    id: "10cric",
    slug: "10cric",
    name: "10CRIC",
    logoUrl: "https://www.google.com/s2/favicons?domain=10cric.com&sz=256",
    rating: 9.7,
    starRating: 5,
    averageUserRating: 5.0,
    totalReviewsCount: 39396,
    badges: ["Made for India", "Fast UPI Withdrawals", "Exclusive Cricket Odds"],
    bonusText: "150% Welcome Bonus up to ₹30,000",
    promoCode: "10CRICVIP",
    rawAffiliateUrl: "https://www.10cric.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 760,
    copiesCount: 340,
    category: "Indian Sportsbook"
  ,
    metaTitle: "10CRIC Promo Code 10CRICVIP | Best Bonus 2026",
    metaDescription: "Use verified promo code 10CRICVIP for 10CRIC to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "10cric promo code, 10cric bonus, 10CRICVIP, best 10cric promo"
  },
  {
    id: "22bet",
    slug: "22bet",
    name: "22Bet India",
    logoUrl: "https://www.google.com/s2/favicons?domain=22bet.in&sz=256",
    rating: 9.4,
    starRating: 4,
    averageUserRating: 4.9,
    totalReviewsCount: 21739,
    badges: ["Huge Markets", "Hindi UI", "Paytm/UPI Accepted"],
    bonusText: "100% Bonus up to ₹10,000",
    promoCode: "22MAX",
    rawAffiliateUrl: "https://22bet.in/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 650,
    copiesCount: 220,
    category: "Sportsbook & Casino"
  ,
    metaTitle: "22Bet India Promo Code 22MAX | Best Bonus 2026",
    metaDescription: "Use verified promo code 22MAX for 22Bet India to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "22bet india promo code, 22bet india bonus, 22MAX, best 22bet india promo"
  },
  {
    id: "melbet",
    slug: "melbet",
    name: "Melbet",
    logoUrl: "https://www.google.com/s2/favicons?domain=melbet.com&sz=256",
    rating: 9.3,
    starRating: 4,
    averageUserRating: 4.8,
    totalReviewsCount: 19967,
    badges: ["Fast Registration", "UPI/IMPS", "High Casino RTP"],
    bonusText: "100% Sports Bonus up to ₹20,000",
    promoCode: "MELBETINDIA",
    rawAffiliateUrl: "https://melbet.com/en/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 810,
    copiesCount: 400,
    category: "Sportsbook"
  ,
    metaTitle: "Melbet Promo Code MELBETINDIA | Best Bonus 2026",
    metaDescription: "Use verified promo code MELBETINDIA for Melbet to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "melbet promo code, melbet bonus, MELBETINDIA, best melbet promo"
  },
  {
    id: "megapari",
    slug: "megapari",
    name: "Megapari",
    logoUrl: "https://www.google.com/s2/favicons?domain=megapari.com&sz=256",
    rating: 9.2,
    starRating: 4,
    averageUserRating: 4.9,
    totalReviewsCount: 21676,
    badges: ["Low Minimum Deposit", "Crypto & INR", "Live Cricket"],
    bonusText: "100% Bonus up to ₹26,000",
    promoCode: "MEGA26K",
    rawAffiliateUrl: "https://megapari.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 520,
    copiesCount: 190,
    category: "Sportsbook"
  ,
    metaTitle: "Megapari Promo Code MEGA26K | Best Bonus 2026",
    metaDescription: "Use verified promo code MEGA26K for Megapari to claim your exclusive welcome bonus. Fast sign-up, instant withdrawals, and top rewards.",
    metaKeywords: "megapari promo code, megapari bonus, MEGA26K, best megapari promo"
  }  ,
  {
    id: "bet365",
    slug: "bet365",
    name: "Bet365",
    logoUrl: "https://www.google.com/s2/favicons?domain=bet365.com&sz=256",
    rating: 9.9,
    starRating: 5,
    averageUserRating: 4.7,
    totalReviewsCount: 27815,
    badges: ["Global #1", "Most Trusted", "Fully Legal", "Live Streaming"],
    bonusText: "15% in Bet Credits up to ₹4,000",
    promoCode: "365WIN",
    rawAffiliateUrl: "https://www.bet365.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: true,
    featuredRank: 1,
    isActive: true,
    clicksCount: 9540,
    copiesCount: 4210,
    category: "Sportsbook",
    metaTitle: "Bet365 Promo Code 365WIN | Best Global Bookmaker",
    metaDescription: "Bet365 is the most trusted global bookmaker. Use promo code 365WIN for best welcome bonuses and live sports streaming.",
    metaKeywords: "bet365, bet365 promo code, bet365 india, legal betting"
  },
  {
    id: "leovegas",
    slug: "leovegas",
    name: "LeoVegas",
    logoUrl: "https://www.google.com/s2/favicons?domain=leovegas.com&sz=256",
    rating: 9.8,
    starRating: 5,
    averageUserRating: 4.9,
    totalReviewsCount: 35224,
    badges: ["King of Casino", "MGA License", "Award Winning App"],
    bonusText: "100% up to ₹80,000 + 200 Free Spins",
    promoCode: "LEOVIP",
    rawAffiliateUrl: "https://www.leovegas.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 8120,
    copiesCount: 3950,
    category: "Legal Casino & Sports",
    metaTitle: "LeoVegas Promo Code LEOVIP | King of Casino",
    metaDescription: "Join LeoVegas, the award-winning online casino. Claim up to ₹80,000 in welcome bonuses with our exclusive LEOVIP code.",
    metaKeywords: "leovegas, leovegas promo code, legal casino india"
  },
  {
    id: "888sport",
    slug: "888sport",
    name: "888sport",
    logoUrl: "https://www.google.com/s2/favicons?domain=888sport.com&sz=256",
    rating: 9.6,
    starRating: 5,
    averageUserRating: 4.7,
    totalReviewsCount: 36094,
    badges: ["UKGC Licensed", "Established 1997", "Daily Boosts"],
    bonusText: "Bet €10 Get €30 in Free Bets",
    promoCode: "888MAX",
    rawAffiliateUrl: "https://www.888sport.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 6200,
    copiesCount: 2980,
    category: "Regulated Sportsbook",
    metaTitle: "888sport Promo Code 888MAX | Free Bets 2026",
    metaDescription: "Bet securely with 888sport, a fully licensed UKGC operator. Use code 888MAX for an exclusive bet €10 get €30 offer.",
    metaKeywords: "888sport, 888sport promo, trusted sportsbook"
  },
  {
    id: "unibet",
    slug: "unibet",
    name: "Unibet",
    logoUrl: "https://www.google.com/s2/favicons?domain=unibet.com&sz=256",
    rating: 9.7,
    starRating: 5,
    averageUserRating: 4.9,
    totalReviewsCount: 33707,
    badges: ["Kindred Group", "Award Winning", "Safe Betting"],
    bonusText: "Money Back as Bonus up to €40",
    promoCode: "UNIVIP",
    rawAffiliateUrl: "https://www.unibet.com/?ref=YOUR_ID",
    masterPartnerUrl: "https://1win-partner.com/?p=mpsw",
    isFeatured: false,
    featuredRank: null,
    isActive: true,
    clicksCount: 5400,
    copiesCount: 2150,
    category: "Global Sportsbook",
    metaTitle: "Unibet Promo Code UNIVIP | Trusted Betting 2026",
    metaDescription: "Unibet offers a secure, legal betting environment with incredible odds. Claim your money back bonus today.",
    metaKeywords: "unibet, unibet bonus, legal betting sites"
  }
];

export const initialFakeWinners: WinnerTickerItem[] = [
  { id: "1", userName: "Alex M.", amount: "$450", platformName: "1Win", country: "United States", flagEmoji: "🇺🇸", timeAgo: "12s ago" },
  { id: "2", userName: "Rahul S.", amount: "500% Bonus", platformName: "Mostbet", country: "India", flagEmoji: "🇮🇳", timeAgo: "34s ago" },
  { id: "3", userName: "Lucas R.", amount: "R$ 1,200", platformName: "Pin-Up", country: "Brazil", flagEmoji: "🇧🇷", timeAgo: "1m ago" },
  { id: "4", userName: "David K.", amount: "$1,850", platformName: "1Win", country: "Canada", flagEmoji: "🇨🇦", timeAgo: "2m ago" },
  { id: "5", userName: "Elena P.", amount: "€600", platformName: "Stake", country: "Germany", flagEmoji: "🇩🇪", timeAgo: "3m ago" },
  { id: "6", userName: "Tariq A.", amount: "1,500 AED", platformName: "1Win", country: "UAE", flagEmoji: "🇦🇪", timeAgo: "4m ago" },
  { id: "7", userName: "Mateo G.", amount: "$920", platformName: "BC.Game", country: "Mexico", flagEmoji: "🇲🇽", timeAgo: "5m ago" }
];

export const sampleFaqs = [
  {
    q: "How do I claim my exclusive deposit bonus?",
    a: "Select your preferred platform from our verified list, copy the promo code by clicking 'COPY', then click 'Claim Bonus Now'. Enter the promo code during sign-up to unlock your bonus automatically."
  },
  {
    q: "Are all listed platforms safe and verified?",
    a: "Yes! Every platform featured on our site undergoes strict audit checks for active licensing (e.g. Curacao, MGA), withdrawal speed, SSL encryption, and fair RNG gaming algorithms."
  },
  {
    q: "How fast are withdrawals processed?",
    a: "Most platforms support instant local payment methods (UPI, Pix, Crypto, E-Wallets) with withdrawal processing times ranging from instant up to 15 minutes."
  },
  {
    q: "Do I need KYC verification to start playing?",
    a: "Many of our top-ranked platforms (like 1Win and Stake) allow instant 1-click registration and fast gameplay without mandatory identity verification for initial small payouts."
  },
  {
    q: "Is the Lucky Wheel bonus guaranteed?",
    a: "Yes, every spin on our Lucky Wheel guarantees an exclusive high-tier VIP bonus code that unlocks extra spins and cash deposit matches."
  }
];
